apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapi
spec:
  selector:
    matchLabels:
      app: loginapi
  template:
    metadata:
      labels:
        app: loginapi
    spec:
      containers:
      - name: loginapi
        image: shrade1206/loginapi:latest
        resources:
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loginapi
spec:
  type: NodePort
  selector:
    app: loginapi
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30801
    

