version: "3.8"

services : 
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdata
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - xxx:/var/lib/mysql
      # - ./mysql/my.cnf:/ect/mysql/conf.d/my.cnf
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:5.1.1
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    ports:
      - 8081:80
    restart: unless-stopped

volumes: 
  xxx: 