version: '3.8'

services:
  redis:
    image: redis:6.0
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - xxx:/data
  app:
    image: shrade1206/login:latest
    depends_on:
      - redis
    ports:
      - 8080:8080
    restart: unless-stopped

volumes: 
  xxx: 